
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVCMoneyBank.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Transaction
{

    public int TransactionID { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<int> TransactionTypeFK { get; set; }

    public Nullable<int> CustomerFK { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<decimal> RemainingBalance { get; set; }

    public Nullable<decimal> InitialDepositAmount { get; set; }

}

}
